"""
the dumbest backup plan.
mostly for testing and cases where you have huge over-coverage.
plans on backing up every file within every backup window.
"""
from backdat.file_parsers.fileset import get_fileset_statlist, STAT_KEYS
from backdat.util.get_hostname import get_hostname
from backdat.planners.util import make_plan_line


def make_plan():
    hostname = get_hostname()
    with open("/var/opt/backdat/backup-plan.tsv", 'w') as planfile:
        planfile.write(
            "# !!! this backup plan was generated by backdat         !!!\n" +
            "# !!! changes made will likely be ignored & overwritten !!!\n"
        )
        for fstat in get_fileset_statlist():   # for every file in fileset
            # plan to back it up on the next run
            timestr = "2222-22-22T22:22:22"
            src = hostname + ":" + fstat[STAT_KEYS.SOURCE]

            trg_dir = '/'.join(fstat[STAT_KEYS.SOURCE].split('/')[:-1])
            trg = (  # TODO: replace hardcoded trgt w/ read from resources.json
                "gdrive-ty:/IMARS/backups/backdat/" +
                hostname +
                trg_dir
                # + "/" + str(month)
            )
            planfile.write(make_plan_line(timestr, src, trg))
